export const RENDER_HUB = "RENDER_HUB";
export const GOTO_FRAME = "GOTO_FRAME";

export const REGISTERED_FRAME = "REGISTERED_FRAME";
export const DEREGISTERED_FRAME = "DEREGISTERED_FRAME";
export const RENDER_FRAME = "RENDER_FRAME";
export const RERENDER_FRAME = "RERENDER_FRAME";
export const GOTO_SUBFRAME = "GOTO_SUBFRAME";
export const POP_SUBFRAME = "POP_SUBFRAME";
export const PUSH_SUBFRAME = "PUSH_SUBFRAME";

export const REGISTERED_SUBFRAME = "REGISTERED_SUBFRAME";
export const DEREGISTERED_SUBFRAME = "DEREGISTERED_SUBFRAME";
export const RENDER_SUBFRAME = "RENDER_SUBFRAME";
export const RERENDER_SUBFRAME = "RERENDER_SUBFRAME";
export const GOTO_PAGE = "GOTO_PAGE";


export const REGISTERED_PAGE = "REGISTERED_PAGE";
export const DEREGISTERED_PAGE = "DEREGISTERED_PAGE";
export const RENDER_PAGE = "RENDER_PAGE";
export const RERENDER_PAGE = "RERENDER_PAGE";